Repository remove-bg/remove-bg-cli, pull requests merged in 2022-09, with the labels that each got.

#1 Improved handling of rate limit and processing a large amount of files
  .circleci/config.yml
  cli.js
  lib/functions.js
  lib/options.js
  package-lock.json
  package.json
Labels: size/M

#2 Include semVer tags as pipeline triggers
  .circleci/config.yml
Labels: enhancement, size/XS

#5 command line interface - inverted behaviour of skip png format optimisation
  README.md
  lib/options.js
  package-lock.json
  package.json
Labels: size/XS
